"""Tests for the solution table generated by SolutionInformation."""

from hypothesis import assume, given, settings

from approximate_model_counting import ModelCounter, Status, is_satisfiable

from .strategies import satisfiable_clauses

# --- Basic tests ---


def test_empty_formula_has_single_row_table():
    """An empty formula (always SAT) should have a single row (empty assignment)."""
    mc = ModelCounter([[1, -1]])  # Tautology to get a formula
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE
    table = info.get_solution_table()
    # Table should exist and have at least one row
    assert len(table) >= 1


def test_unit_clause_formula_backbone_not_in_table():
    """Variables in the backbone should not appear in the solution table."""
    mc = ModelCounter([[1], [2, 3]])  # 1 is forced true
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE
    backbone = info.get_backbone()
    assert 1 in backbone
    table = info.get_solution_table()
    # Variable 1 should not be in the table since it's in the backbone
    assert not table.contains(1)


def test_unsatisfiable_formula_empty_table():
    """An UNSAT formula should have an empty solution table."""
    mc = ModelCounter([[1], [-1]])
    info = mc.with_assumptions([])
    assert info.solvable() == Status.UNSATISFIABLE
    table = info.get_solution_table()
    # For UNSAT, the table should be empty (no solutions)
    assert len(table) == 0 or len(table.variables) == 0


def test_simple_sat_table_rows_are_satisfiable():
    """All rows in the solution table should be satisfiable when combined with backbone."""
    mc = ModelCounter([[1, 2], [-1, -2]])  # XOR: exactly one of 1 or 2 is true
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE
    backbone = info.get_backbone()
    table = info.get_solution_table()

    # Each row should be satisfiable with the backbone
    for i in range(len(table)):
        row = table[i]
        assumptions = list(backbone) + list(row)
        assert is_satisfiable([[lit] for lit in assumptions] + [[1, 2], [-1, -2]])


def test_equivalent_variables_only_one_in_table():
    """When two variables are equivalent, only one should appear in the table."""
    # x <-> y (1 <-> 2) with a third free variable z (3)
    # Clauses: [1, -2], [-1, 2] means 1=2
    # Add [1, 3] so there are multiple solutions (1=2=true with z free, or 1=2=false, z=true)
    mc = ModelCounter([[1, -2], [-1, 2], [1, 3]])
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE

    # Verify 1 and 2 are equivalent
    assert info.are_equivalent(1, 2)

    # Check that only one of 1 or 2 is in the table
    table = info.get_solution_table()
    has_1 = table.contains(1)
    has_2 = table.contains(2)
    # At most one of them should be in the table
    assert not (has_1 and has_2), "Both equivalent variables in table"


def test_table_size_limit():
    """Table building stops when size exceeds 10^6 rows."""
    # A single clause with 25 variables: (1 OR 2 OR ... OR 25)
    # This allows 2^25 - 1 satisfying assignments (all except all-false)
    # The table should stop growing before adding all variables
    n_vars = 25
    clauses = [list(range(1, n_vars + 1))]
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE

    # No variables should be in backbone (all can be false in some solution)
    backbone = info.get_backbone()
    assert len(backbone) == 0

    table = info.get_solution_table()
    # Table size should be capped around 10^6
    # 2^20 = 1M, so we expect ~20 variables max
    assert len(table) <= 2**21
    # Not all 25 variables should be in the table due to size limit
    assert len(table.variables) < n_vars, f"All {n_vars} variables in table, size={len(table)}"


def test_table_variables_not_in_backbone():
    """Variables in the solution table should not be in the backbone."""
    mc = ModelCounter([[1], [2, 3], [-2, -3]])  # 1 forced, 2 XOR 3
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE
    backbone = set(info.get_backbone())
    backbone_vars = {abs(lit) for lit in backbone}
    table = info.get_solution_table()

    for var in table.variables:
        assert abs(var) not in backbone_vars


def test_solution_table_with_assumptions():
    """Solution table should respect assumptions."""
    mc = ModelCounter([[1, 2], [2, 3]])
    info = mc.with_assumptions([1])
    assert info.solvable() == Status.SATISFIABLE
    backbone = info.get_backbone()
    assert 1 in backbone  # The assumption should be in backbone
    table = info.get_solution_table()
    # Variable 1 should not be in the table
    assert not table.contains(1)


def test_solution_table_clone_independence():
    """Cloning the solution table should create an independent copy."""
    mc = ModelCounter([[1, 2], [-1, -2]])
    info = mc.with_assumptions([])
    table = info.get_solution_table()
    original_len = len(table)
    clone = table.clone()

    assert len(clone) == original_len
    # Modifications to clone should not affect original
    if original_len > 1 and len(clone.variables) > 0:
        row = clone[0]
        clone.remove_matching(list(row))
        assert len(clone) < original_len
        assert len(table) == original_len


# --- Property-based tests ---


@given(satisfiable_clauses())
@settings(max_examples=100, deadline=None)
def test_table_rows_mostly_satisfiable_with_backbone(clauses):
    """Most rows in the solution table, combined with backbone, should be satisfiable.

    Note: The solution table is an approximation built via random sampling,
    so not every row is guaranteed to be satisfiable. This test checks that
    at least some rows are satisfiable.
    """
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    backbone = info.get_backbone()
    table = info.get_solution_table()
    assume(len(table) > 0)

    # Test a sample of rows and count successes
    num_rows = min(len(table), 10)
    num_sat = 0
    for i in range(num_rows):
        row = table[i]
        assumptions = list(backbone) + list(row)
        test_clauses = clauses + [[lit] for lit in assumptions]
        if is_satisfiable(test_clauses):
            num_sat += 1

    # At least one row should be satisfiable (the table is an over-approximation)
    assert num_sat >= 1, "No rows in table are satisfiable"


@given(satisfiable_clauses())
@settings(max_examples=100, deadline=None)
def test_table_variables_disjoint_from_backbone(clauses):
    """Table variables should be disjoint from backbone variables."""
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    backbone_vars = {abs(lit) for lit in info.get_backbone()}
    table = info.get_solution_table()

    for var in table.variables:
        assert abs(var) not in backbone_vars


@given(satisfiable_clauses())
@settings(max_examples=100, deadline=None)
def test_table_is_not_empty_for_sat(clauses):
    """A satisfiable formula should produce a non-empty solution table."""
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    assert info.solvable() == Status.SATISFIABLE
    table = info.get_solution_table()
    # Table should have at least one row (might be empty assignment if all are backbone)
    assert len(table) >= 1


@given(satisfiable_clauses())
@settings(max_examples=100, deadline=None)
def test_table_row_variables_match(clauses):
    """Each row should contain literals for exactly the table's variables."""
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    table = info.get_solution_table()

    table_vars = set(table.variables)
    for i in range(min(len(table), 10)):
        row = table[i]
        row_vars = {abs(lit) for lit in row}
        assert len(row) == len(table_vars)
        assert row_vars == table_vars


@given(satisfiable_clauses())
@settings(max_examples=50, deadline=None)
def test_table_rows_dont_conflict_with_backbone(clauses):
    """Table rows should not contain negations of backbone literals."""
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    backbone = set(info.get_backbone())
    table = info.get_solution_table()

    for i in range(min(len(table), 10)):
        row = set(table[i])
        for lit in backbone:
            assert -lit not in row


@given(satisfiable_clauses())
@settings(max_examples=50, deadline=None)
def test_removing_rows_reduces_table_size(clauses):
    """Removing rows from the table should reduce its size."""
    mc = ModelCounter(clauses)
    info = mc.with_assumptions([])
    table = info.get_solution_table()

    if len(table) < 2 or len(table.variables) == 0:
        return  # Nothing meaningful to test

    # Clone the table and remove some rows
    clone = table.clone()
    original_len = len(clone)
    row_to_remove = clone[0]
    clone.remove_matching(list(row_to_remove))

    # Table should be smaller after removal
    assert len(clone) < original_len
